package com.fmrpg.fmbackend.seeders;

import com.fmrpg.fmbackend.entities.characterpkg.CharacterClass;
import com.fmrpg.fmbackend.entities.characterpkg.ClassAbility;
import com.fmrpg.fmbackend.repositories.CharacterClassRepository;
import com.fmrpg.fmbackend.repositories.ClassAbilityRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

@Component
@RequiredArgsConstructor
public class ClassAbilityFighterSeeder implements CommandLineRunner {

    private final ClassAbilityRepository classAbilityRepository;
    private final CharacterClassRepository characterClassRepository;

    @Override
    @Transactional
    public void run(String... args) throws Exception {


        CharacterClass fighter = characterClassRepository.findByName("Lutador").orElseThrow();


        List<ClassAbility> classAbilities = new ArrayList<>(List.of(
                // Level 2 abilities
                new ClassAbility("Aparar Ataque", "Você rebate um ataque com outro ataque, assim conseguindo aparar um golpe. Quando for alvo de um ataque corpo a corpo, você pode gastar 1PE e sua reação para realizar uma jogada de ataque contra o atacante. Caso seu teste supere o do inimigo, você evita o ataque", 2, List.of(fighter)),
                new ClassAbility("Aparar Projéteis", "Utilizando de sua agilidade e reflexos, você consegue tentar aparar projéteis em sua direção, reduzindo o dano deles. Quando receber um ataque à distância, você pode gastar 1 PE e sua reação para tentar aparar o projétil, reduzindo o dano recebido em 2d6 + modificador de atributo-chave + bônus de treinamento.", 2, List.of(fighter)),
                new ClassAbility("Ataque Inconsequente", "Você baixa a guarda para atacar de maneira inconsequente, aumentando seu potencial de dano. Uma vez por rodada, ao realizar um ataque, você pode escolher receber vantagem na jogada de ataque e +5 na rolagem de dano dele. Porém, ao realizar um ataque inconsequente, você fica Desprevenido por 1 rodada.", 2, List.of(fighter)),
                new ClassAbility("Caminho da Mão Vazia", "Mesmo diante a possibilidade de brandir armas marciais, você decide se ater as mãos vazias e se aperfeiçoar nesse caminho. Todo ataque desarmado que você realizar causa dano adicional igual ao seu bônus de treinamento e você soma metade do seu bônus de treinamento em jogadas de ataque desarmados.", 2, List.of(fighter)),
                new ClassAbility("Complementação Marcial", "Suas habilidades marciais complementam certas manobras, deixando-as mais eficientes. Enquanto estiver desarmado ou empunhando uma arma marcial, você recebe um bônus de +2 em testes para Desarmar, Derrubar ou Empurrar, assim como para resistir a esses efeitos.", 2, List.of(fighter)),
                new ClassAbility("Deboche Desconcertante", "Cheio de si, você consegue debochar de um inimigo de uma maneira que o desconcerta. Como uma Ação Bônus, escolha uma criatura que possa te ver ou ouvir: realize um teste de Intimidação contra um teste de Vontade dela, no qual você recebe um bônus de +2. Caso você suceda, a criatura recebe uma penalidade igual ao seu bônus de treinamento em todos os testes que ela realizar até o começo do seu próximo turno.", 2, List.of(fighter)),
                new ClassAbility("Dedicação em Arma", "Ao invés de contar apenas com seus punhos, você se dedica a certas armas. Escolha três armas para serem suas Armas Dedicadas, as quais não podem possuir as propriedades Duas Mãos ou Pesada. Suas armas escolhidas passam a ser contadas como marciais, se não forem, e enquanto empunhar uma Arma Dedicada, o dano dela aumenta em 1 nível.", 2, List.of(fighter)),
                new ClassAbility("Esquiva Rápida", "Com agilidade, você se prepara para esquivar de ataques. Como uma Ação Bônus, realize um teste de Acrobacia contra a Atenção de um inimigo dentro do seu alcance corpo a corpo. Caso suceda no teste, o alvo recebe metade do seu modificador de Destreza como penalidade em jogadas de ataque feitas contra você até o começo do seu próximo turno.", 2, List.of(fighter)),
                new ClassAbility("Finta Melhorada", "Você desenvolva sua finta para que se torne mais eficiente e se adaptar ao seu corpo. Você pode optar por utilizar Destreza ao invés de Presença em testes de Enganação para fintar. Além disso, acertar um inimigo desprevenido pela sua finta causa um dado de dano adicional.", 2, List.of(fighter)),
                new ClassAbility("Impacto Misto", "Você consegue misturar o uso de armas adequadas com seus ataques desarmados. Quando acertar uma criatura com um ataque com arma marcial, você recebe +2 em jogadas de ataque e dano desarmados até o começo do seu próximo turno.", 2, List.of(fighter)),
                new ClassAbility("Kiai Intimidador", "Sendo a exteriorização da energia e força corporal, um kiai é liberado diante um bom golpe, intimidando com um grito. Uma vez por rodada, quando conseguir um crítico em um ataque corpo a corpo você pode, como uma ação livre, realizar um teste de Intimidação contra Vontade do alvo e, caso suceda, ela fica Abalada por uma rodada.", 2, List.of(fighter)),
                new ClassAbility("Mãos Amaldiçoadas", "Como um feiticeiro, você consegue incorporar o jujutsu em seu combate a curta distância. Quando utilizar um Feitiço ofensivo com alcance de Toque, você pode substituir a jogada de ataque de técnica por uma jogada de ataque corpo a corpo e, também, somar seu modificador de Força ou Destreza no total.", 2, List.of(fighter)),
                new ClassAbility("Puxar um Ar", "Você consegue respirar fundo e puxar as forças guardadas em seu interior para continuar lutando. Você pode, como uma Ação Bônus, realizar uma rolagem do seu dano desarmado e se curar nesse valor. Esta habilidade pode ser usada uma quantidade de vezes igual ao seu bônus de treinamento, por descanso curto ou longo.", 2, List.of(fighter)),
                new ClassAbility("Quebrando Tudo", "O cenário e ambiente ao seu redor conta com várias armas e, lutando para quebrar tudo, você aprimora seu uso de armas improvisadas. Como parte de um ataque, você pode agarrar um objeto pequeno ou menor adjacente a você. Objetos usados de arma improvisada recebem +1d no dano e são considerados armas marciais.", 2, List.of(fighter)),
                new ClassAbility("Resistir", "Você pode utilizar da energia para fortalecer seu corpo e resistir com mais eficiência. Quando realizar um teste de resistência de Fortitude ou Reflexos, você pode gastar até 2PE para receber um bônus de +2 para cada PE gasto.", 2, List.of(fighter)),

                // Level 4 abilities
                new ClassAbility("Ação Ágil", "Você otimiza o seu tempo de ação. Uma vez por rodada, você pode gastar 2PE para receber uma Ação Ágil, a qual pode ser utilizada para Andar, Desengajar ou Esconder.", 4, List.of(fighter)),
                new ClassAbility("Acrobata", "Ao invés da força, você usa a agilidade para poder saltar. Você passa a utilizar Destreza como atributo para calcular sua distância de pulo, assim como pode utilizar Acrobacia no lugar de Atletismo em testes para aumentar a sua distância de salto.", 4, List.of(fighter)),
                new ClassAbility("Atacar e Recuar", "Você consegue atacar e aproveitar a brecha do golpe para se afastar do inimigo. Uma vez por turno, quando acertar uma criatura com um ataque, você pode gastar 1 PE para se mover até 4,5 metros para longe da criatura acertada. Este movimento não causa ataques de oportunidade.", 4, List.of(fighter), classAbilityRepository.findByName("Esquiva Rápida")),
                new ClassAbility("Brutalidade", "Existe uma brutalidade guardada no seu interior, a qual pode ser canalizada como uma fúria para combate. Como uma Ação Livre, você pode gastar 2PE para adentrar no estado de Brutalidade: enquanto nesse estado, você recebe +2 em jogadas de ataque corpo a corpo e dano.", 4, List.of(fighter)),
                new ClassAbility("Defesa Marcial", "Você é capaz de incorporar a leveza de seus movimentos em sua defesa. Enquanto estiver desarmado ou empunhando uma arma marcial, você soma 1 + metade do seu Bônus de Treinamento à sua Defesa.", 4, List.of(fighter), classAbilityRepository.findByName("Complementação Marcial")),
                new ClassAbility("Devolver Projéteis", "Sua capacidade de aparar é aprimorada, abrindo também oportunidades para os devolver. O dado de Aparar Projéteis se torna 3d10 e soma também o seu Nível de Lutador. Caso você use Aparar Projéteis e o dano se torne nulo ou negativo, você pode devolver o projétil como parte da reação.", 4, List.of(fighter), classAbilityRepository.findByName("Aparar Projéteis")),
                new ClassAbility("Fluxo", "Conforme se empolga, você cada vez mais se aproxima de entrar 'na zona', um estado de completo foco e imersão na luta. A cada nível de empolgação que você subir, você recebe +1 em rolagens de acerto e de dano, até um máximo de +4, com nível de empolgação 5.", 4, List.of(fighter)),
                new ClassAbility("Fúria da Vingança", "Seus aliados são importantes, e você irá vingá-los caso necessário. Ao ver um personagem aliado (Invocações não são consideradas) chegar a 0 pontos de vida e cair, você recebe os seguintes benefícios durante uma rodada: seus ataques causam 4 de dano adicional; sua Defesa aumenta em 2; você recebe +2 em TRs de Fortitude e Vontade.", 4, List.of(fighter)),
                new ClassAbility("Imprudência Motivadora", "Em certos momentos, ser imprudente e se desafiar o motiva a triunfar. Ao iniciar uma cena de combate, você pode escolher lutar com uma restrição auto imposta, escolha um dos seus sensos ou membros (como não usar a visão ou não usar uma das pernas), até o final da cena, recebe as mesmas penalidades de perder um membro.", 4, List.of(fighter)),
                new ClassAbility("Músculos Desenvolvidos", "Sua força o fez ter músculos desenvolvidos, os quais por consequência acabaram ficando mais preparados para receber golpes, sendo mais difícil o acertar de maneira efetiva. Ao obter esta habilidade, você pode optar por somar seu Modificador de Força ao invés de Destreza em sua Defesa, modificando o cálculo padrão.", 4, List.of(fighter)),
                new ClassAbility("Redirecionar Força", "Você consegue redirecionar um golpe direcionado a você, mudando o alvo. Quando um inimigo errar um ataque corpo a corpo contra você, você pode gastar 2PE e sua reação para tentar redirecionar o ataque: escolha outra criatura dentro do alcance do golpe e, caso o resultado da jogada de ataque dela seja superior à Defesa do novo alvo, ele recebe o ataque.", 4, List.of(fighter)),
                new ClassAbility("Segura Pra Mim", "Uma criatura agarrada pode ser utilizada como escudo. Quando for alvo de um ataque corpo a corpo ou uma habilidade com alvo único, você pode gastar 3 PE para tentar colocar uma criatura que esteja agarrando na frente, faça um teste de Atletismo contra o Atletismo ou Acrobacia da criatura agarrada.", 4, List.of(fighter)),
                new ClassAbility("Sobrevivente", "Como um lutador, você deve sobreviver, recuperando-se quando sente a vitalidade esvaindo. Enquanto estiver com menos da metade dos seus pontos de vida máximos, sempre que começar seu turno, você recupera 1d6 + seu modificador de Constituição em pontos de vida.", 4, List.of(fighter)),
                new ClassAbility("Voadora", "Você consegue investir em uma voadora, acumulando potência conforme a distância aumenta. Quando realizar uma Investida, e estiver desarmado, você pode gastar 3PE para realizar uma Voadora. Caso o faça, você causa 1d8 de dano adicional para cada 3 metros que se deslocar até o alvo, limitado pelo seu modificador de Força ou Destreza.", 4, List.of(fighter)),

                // Level 6 abilities
                new ClassAbility("Aprimoramento Marcial", "Você aprimora suas habilidades marciais para deixar mais difícil resistir as suas técnicas de Lutador. Você passa a somar metade do seu Bônus de Treinamento em sua CD de Especialização.", 6, List.of(fighter)),
                new ClassAbility("Ataque Extra", "Você consegue atacar mais rápido, otimizando seus golpes. Ao realizar a ação Atacar, você pode gastar 2 PE para atacar duas vezes ao invés de uma.", 6, List.of(fighter)),
                new ClassAbility("Brutalidade Sanguinária", "Em meio a brutalidade, o sangue pode o renovar. Enquanto no estado de Brutalidade, sempre que tiver um acerto crítico ou reduzir a vida de uma criatura a 0 ou menos, você aumenta o nível de dano dos seus ataques corpo a corpo em 1, acumulando até um limite igual ao seu bônus de treinamento.", 6, List.of(fighter), classAbilityRepository.findByName("Brutalidade")),
                new ClassAbility("Corpo Calejado", "De tanto combater e receber golpes, todo seu corpo já está calejado e mais resistente. Você passa a adicionar metade do seu Modificador de Constituição na sua Defesa e recebe pontos de vida adicionais igual ao seu nível de Lutador.", 6, List.of(fighter)),
                new ClassAbility("Eliminar e Continuar", "Eliminar um inimigo e o ver cair serve apenas como um incentivo para continuar. Sempre que um inimigo ao qual você causou dano cair ou morrer dentro de 9 metros, você recebe 2d6 + nível de personagem + modificador de atributo-chave em PV temporários.", 6, List.of(fighter)),
                new ClassAbility("Foguete sem Ré", "Se dedicando a avançar sem olhar para trás, você consegue usar da sua energia para o impulsionar em uma investida direta. Como uma ação completa, você gasta 6 PE para se mover até uma distância igual ao dobro do seu deslocamento; sempre que passar por uma criatura durante essa investida, ela deve realizar um teste de resistência de Reflexos.", 6, List.of(fighter)),
                new ClassAbility("Golpe da Mão Aberta", "Você é capaz de realizar um ataque potente, utilizando a palma da mão. Como uma ação comum, você pode gastar 4 PE para realizar um golpe de mão aberta. Você realiza um ataque desarmado contra um alvo dentro do seu alcance corpo a corpo e, em um acerto, ele deve realizar um teste de resistência de Fortitude.", 6, List.of(fighter)),
                new ClassAbility("Ignorar Dor", "Seu desejo por uma boa luta é constante, permitindo-o até mesmo ignorar parte da dor que seja infligida em você. Você recebe redução de danos contra todos os tipos, menos alma, igual ao seu nível de empolgação atual. Contra danos físicos, a redução de dano é dobrada.", 6, List.of(fighter)),
                new ClassAbility("Manobras Finalizadoras", "Após toda uma sequência empolgante, você sabe exatamente como finalizar o seu combo com uma manobra ainda mais impactante. Você libera acesso a novas manobras, listadas no final da especialização. Ao realizar um ataque, você pode realizar uma Manobra Finalizadora.", 6, List.of(fighter)),
                new ClassAbility("Poder Corporal", "Cultivando e priorizando seu próprio corpo, você expande o poder dele. O dano de seus ataques desarmados aumenta em 2 níveis e, uma vez por rodada, ao realizar um ataque desarmado, você pode escolher realizar uma Manobra como parte do ataque, aplicando seu efeito juntamente do dano.", 6, List.of(fighter), classAbilityRepository.findByName("Caminho da Mão Vazia")),
                new ClassAbility("Potência Superior", "A potência que você consegue colocar em suas manobras se torna superior. Quando Derrubar um inimigo com sucesso, ele também recebe 2d6 + seu modificador de Força de dano de impacto; quando Empurrar um inimigo, a distância padrão se torna 4,5 metros ao invés de 1,5 metros.", 6, List.of(fighter), classAbilityRepository.findByName("Complementação Marcial")),
                new ClassAbility("Sequência Inconsequente", "Não se limitando a apenas um ataque, você assume uma postura inconsequente durante todo seu período de atacar. Quando utilizar Ataque Inconsequente, você passa a receber o dano adicional em todos seus ataques realizados durante o turno.", 6, List.of(fighter), classAbilityRepository.findByName("Ataque Inconsequente")),
                new ClassAbility("Um Com a Arma", "Você começa a se tornar apenas um com as armas para as quais se dedicou. Uma quantidade de vezes igual a metade do seu nível de Lutador, por descanso curto, suas armas dedicadas conseguem superar resistência ao tipo de dano delas em um ataque.", 6, List.of(fighter), classAbilityRepository.findByName("Dedicação em Arma")),

                // Level 8 abilities
                new ClassAbility("Aptidões de Luta", "Você aprimora suas aptidões de energia necessárias para a luta. Ao obter esta habilidade, você pode aumentar o seu nível de aptidão em Aura ou Controle e Leitura em 1. Você pode pegar esta habilidade duas vezes, uma para cada aptidão.", 8, List.of(fighter)),
                new ClassAbility("Ataques Ressonantes", "O impacto dos seus ataques ressoa e atinge outros inimigos próximos do seu alvo. Ao realizar um ataque contra um inimigo, você pode gastar 2 pontos de energia amaldiçoada para que todos os inimigos adjacentes ao alvo, com a Defesa inferior ao resultado do seu ataque, recebam dano igual a metade do dano causado no alvo.", 8, List.of(fighter)),
                new ClassAbility("Brutalidade Aprimorada", "Aprimorando no fluxo que você impõe no seu corpo, ele te deixa ainda mais resistente. Ao entrar no estado de brutalidade, você recebe uma quantidade de pontos de vida temporários igual ao seu nível + modificador do atributo para CD de Especialização. O bônus inicial em dano se torna +4 e o aumento no dano por ponto de energia adicional gasto se torna +2.", 8, List.of(fighter), classAbilityRepository.findByName("Brutalidade")),
                new ClassAbility("Feitiço e Punho", "Com precisão, você consegue agir rapidamente para utilizar do jujutsu e complementar com seu corpo. Uma vez por rodada, quando utilizar um Feitiço de dano com alvo único, você pode gastar 2PE para realizar um ataque corpo a corpo contra o mesmo alvo, desde que ele esteja dentro do seu alcance.", 8, List.of(fighter), classAbilityRepository.findByName("Mãos Amaldiçoadas")),
                new ClassAbility("Golpear Brecha", "Você consegue aproveitar de um golpe aparado para atacar a brecha que se abre na defesa do inimigo. Quando utilizar Aparar Ataque e conseguir aparar com sucesso, você pode gastar 2PE adicionais para realizar um ataque contra o inimigo como parte da reação.", 8, List.of(fighter), classAbilityRepository.findByName("Aparar Ataque")),
                new ClassAbility("Oportunista", "Você sabe aproveitar bem brechas na defesa dos inimigos. Uma vez por rodada, quando um inimigo dentro do seu alcance corpo a corpo é atingido por um ataque de uma criatura o flanqueando, você pode gastar 2 PE para fazer um ataque corpo a corpo contra a criatura.", 8, List.of(fighter)),
                new ClassAbility("Pancada Desnorteante", "Uma boa pancada deixa qualquer um despreparado para o que vem a seguir. Quando conseguir um acerto crítico em um ataque corpo a corpo, você pode fazer com que o alvo do ataque receba desvantagem contra um TR à sua escolha, até o início do seu próximo turno.", 8, List.of(fighter)),
                new ClassAbility("Punhos Letais", "Não há necessidade de armas se o seu corpo já é a mais letal entre elas. Enquanto estiver desarmado, sua margem de crítico diminui em 1 e seus ataques ignoram RD igual ao seu bônus de treinamento.", 8, List.of(fighter), classAbilityRepository.findByName("Poder Corporal")),

                // Level 10 abilities
                new ClassAbility("Alma Quieta", "Sua alma é imperturbável durante uma boa luta. Você recebe vantagem para resistir às seguintes condições: Condenado, Enfeitiçado e Fragilizado.", 10, List.of(fighter)),
                new ClassAbility("Corpo Sincronizado", "Seu corpo está sempre em sincronia. Você recebe vantagem para resistir às seguintes condições: Caído e Exposto.", 10, List.of(fighter)),
                new ClassAbility("Empolgar-se", "Em certos momentos, a própria antecipação que você guarda para uma luta pode se transformar na empolgação necessária. Uma quantidade de vezes igual ao seu Bônus de treinamento, por descanso longo, você pode escolher subir dois níveis de empolgação, ao invés de um, no começo de um turno em que ele aumentaria.", 10, List.of(fighter)),
                new ClassAbility("Impacto Demolidor", "Você consegue colocar tanta força em um golpe que o alvo se torna uma bola de demolição. Como uma Ação Comum, realize uma jogada de ataque corpo a corpo contra um alvo dentro do seu alcance corpo a corpo e, caso acerte, você causa o dano do ataque e realiza a ação Empurrar como parte dele.", 10, List.of(fighter), classAbilityRepository.findByName("Potência Superior")),
                new ClassAbility("Insistência", "Deixando o seu desejo se ampliar ainda mais, você se torna um lutador insistente e difícil de derrubar. Uma vez por cena, caso você fosse ter os seus pontos de vida reduzidos a 0, você pode escolher retornar ao nível de empolgação 1 para continuar de pé, curando-se em um valor igual a uma rolagem de dano do seu ataque desarmado.", 10, List.of(fighter), classAbilityRepository.findByName("Ignorar Dor")),
                new ClassAbility("Mente em Paz", "Sua mente continua em paz mesmo durante o combate. Você recebe vantagem para resistir às seguintes condições Amedrontado, Atordoado e Confuso.",10 , List.of(fighter)),

                // Level 12 abilities
                new ClassAbility("Armas Absolutas", "Sua dominância com as Armas Dedicadas chega ao ápice, tornando-as uma parte íntegra de si mesmo. Enquanto estiver empunhando uma Arma Dedicada, você pode gastar 2PE para receber os seguintes bônus por uma rodada: você escolhe aumentar sua Defesa em 3 ou receber +3 em Jogadas de Ataque.", 12, List.of(fighter), classAbilityRepository.findByName("Um Com a Arma")),
                new ClassAbility("Corpo Arsenal", "Você se torna plenamente consciente do complexo arsenal que o seu corpo é, podendo o utilizar ofensivamente de diferentes maneiras. Quando realizar um acerto crítico com um ataque desarmado, você pode optar por infligir o efeito de um grupo adicional entre Bastão, Haste ou Martelo.", 12, List.of(fighter), classAbilityRepository.findByName("Punhos Letais")),
                new ClassAbility("Seja Água", "Não se colocando dentro de uma única forma, você aprende a se mover como a água, adaptando-se e não se prendendo. Seu Deslocamento aumenta em 3 metros, você ignora terreno difícil por fontes físicas (como detritos ou solo destruído) e, uma vez por rodada, pode evitar ser agarrado sem a necessidade de teste.", 12, List.of(fighter)),
                new ClassAbility("Tempestade Sufocante", "Seus golpes marciais são tão rápidos e potentes que se tornam uma tempestade que sufoca e destrói a guarda dos inimigos. Para cada ataque corpo a corpo desarmado ou com arma marcial que você acertar em um mesmo alvo, ele recebe -1 na Defesa e em Testes de Resistência realizados contra você.", 12, List.of(fighter)),

                // Level 16 abilities
                new ClassAbility("Corpo Supremo", "Você alcançou um alto nível como lutador e levou seu corpo ao limite. Você recebe mais 3 metros de movimento adicionais, +4 na sua Defesa e redução de dano igual a metade do seu nível de personagem contra dano cortante, perfurante e de impacto.", 16, List.of(fighter)),
                new ClassAbility("Duro na Queda", "Quando estiver nas portas da morte, você pode escolher receber uma falha garantida para fazer um teste de Vontade contra a CD X, sendo X igual a 15 + 1 para cada 3 pontos de vida negativos. Se passar, você levanta com 1 de vida e recebe 1 ponto de exaustão.", 16, List.of(fighter))
        ));

        if (classAbilityRepository.count() == 0) {
            classAbilityRepository.saveAll(classAbilities);

            Map<String, ClassAbility> abilityMap = classAbilities.stream()
                    .collect(Collectors.toMap(ClassAbility::getName, Function.identity()));
            fighter.setAvailableAbilities(new ArrayList<>(abilityMap.values()));
            characterClassRepository.save(fighter);
        } else {
            System.out.println("Class abilities already exist in the database, skipping seeding.");
        }
    }
}
