package com.fmrpg.fmbackend.seeders;

import com.fmrpg.fmbackend.entities.characterpkg.CharacterFeat;
import com.fmrpg.fmbackend.repositories.FeatRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
@RequiredArgsConstructor
public class FeatSeeder implements CommandLineRunner {

    private final FeatRepository featRepository;



    @Override
    public void run(String... args) throws Exception {

        if(featRepository.count() == 0 ) {
            List<CharacterFeat> feats = new ArrayList<>(
                    List.of(
                            new CharacterFeat("Afinidade com Técnica", "Com uma afinidade superior com a sua técnica amaldiçoada, você consegue a desenvolver melhor, criando mais extensões dela. Ao obter esse talento, você recebe um Feitiço adicional. Nos níveis 5, 10, 15 e 20 você recebe mais um Feitiço adicional.", ""),
                            new CharacterFeat("Artesão Amaldiçoado", "A criação de ferramentas amaldiçoadas é um ofício no qual você busca se especializar. Ao obter este talento, você se torna capaz de criar Ferramentas Amaldiçoadas, de acordo com o guia na página 154. Além disso, você se torna treinado em Ofício (Ferreiro) ou Ofício (Canalizador), caso não seja treinado; caso já seja treinado em ambas, você se torna mestre em uma delas à sua escolha.", ""),
                            new CharacterFeat("Ataque Infalível", "Uma vez por rodada, após a rolagem de dano de um ataque armado ou desarmado, você pode escolher a repetir, ficando com o novo resultado obrigatoriamente. Além disso, você não pode ter os níveis de dano da sua arma reduzidos.", ""),
                            new CharacterFeat("Atenção Infalível", "Sua atenção para os arredores nunca falha, mantendo seus sentidos afiados. Você recebe um bônus de +5 em sua Atenção e não pode ser surpreendido caso consciente.", ""),
                            new CharacterFeat("Dedicação Recompensadora", "Você se dedica mais do que o normal em suas missões, imagem e desempenho, e recebe melhores recompensas, em troca. No quarto grau, você recebe dois itens de custo 1 a mais; no terceiro grau, você recebe dois itens de custo 2 a mais; no segundo grau, você recebe um item de custo 2 a mais e 2 de custo 3 a mais; no primeiro grau, você recebe dois itens de custo 3 a mais e um item de custo 4 a mais e, no grau especial, você recebe dois itens de custo 4 a mais. Os aumentos de itens não são cumulativos.", ""),
                            new CharacterFeat("Favorecido pela Sorte", "Você tem uma sorte inexplicável, a qual o favorece nos momentos mais críticos. Você tem 3 pontos de sorte. Sempre que fizer uma rolagem, você pode gastar um ponto de sorte para rolar outro d20, podendo escolher usar qualquer um dos dois resultados. Você pode escolher rolar o outro dado após ver o resultado da primeira rolagem, mas antes de ver as consequências. Quando um inimigo conseguir um 20 em uma jogada de ataque para o acertar, você recupera 1 ponto de sorte. Você recupera seus pontos de sorte após um descanso longo.", ""),
                            new CharacterFeat("Guarda Infalível", "Você nunca baixa a sua guarda, mesmo em uma situação que pode ser vista como catastrófica. Em caso de um desastre em um teste de ataque, você não causa um ataque como reação. Caso um efeito imposto sobre você tente reduzir sua Defesa ou impor modificadores negativos em testes de resistência, você terá +3 para resistir.", ""),
                            new CharacterFeat("Incremento de Atributo", "Buscando se tornar mais forte, você aumenta um de seus atributos através do treino e esforço. Ao obter esse talento, você aumenta o valor e o limite de um atributo à sua escolha em 2. Você pode pegar este talento várias vezes, mas apenas uma vez para cada atributo.", ""),
                            new CharacterFeat("Investida Aprimorada", "Você domina a arte de realizar uma investida, otimizando-a para extrair o potencial máximo da ação. Ao realizar uma ação de investida, seu movimento aumenta em 3 metros durante ela; o bônus de acerto aumenta de +2 para um valor igual ao seu bônus de treinamento e, caso acerte o ataque, o alvo deve realizar um teste de Atletismo contra o seu, sendo derrubado em uma falha.", ""),
                            new CharacterFeat("Mestre das Armas", "Você desenvolve suas capacidades e potencial para manejar armas. Ao obter este talento, você escolhe aumentar o valor de sua Força ou Destreza em 2 e pode escolher entre se tornar treinado em quatro armas quaisquer à sua escolha ou receber acesso ao efeito de crítico de um grupo de armas à sua escolha.", ""),
                            new CharacterFeat("Mestre Defensivo", "Você desenvolve suas capacidades de defesa e resistência. Ao obter este talento, você escolhe aumentar o valor de sua Força ou Constituição em 2 e se torna treinado em escudos. Caso já seja treinado, você recebe Redução de Dano adicional com o escudo igual a metade do valor base de RD dele (um Escudo Pesado concederia 9 ao invés de 6).", ""),
                            new CharacterFeat("Perceber Oportunidade", "Você possui uma facilidade sem igual para realizar golpes oportunos, sendo quase como uma segunda natureza para você. Você ignora a regra de repetição de reação para Golpes de Oportunidade, podendo repeti-lo duas vezes por rodada ao invés do comum. Todo golpe de oportunidade que você realiza possui vantagem.", ""),
                            new CharacterFeat("Provocação Desafiadora", "Não só provocar, mas você é capaz de se transformar no centro da atenção daquele que você deseja desafiar. Uma criatura que seja afetada por uma ação de Provocar sua, além de receber desvantagem para atacar outras criaturas, deve sempre realizar pelo menos um ataque contra você. Além disso, uma quantidade de vezes igual a metade do seu modificador de Carisma, você pode utilizar Provocar como uma Ação Livre.", ""),
                            new CharacterFeat("Resiliência Melhorada", "Você refina suas estratégicas e habilidade para resistir a um nicho específico de ameaças. Ao obter este talento, escolha um teste de resistência, exceto Integridade: você se torna treinado nele ou, caso já seja treinado, se torna mestre. O valor do atributo usado no TR escolhido aumenta em 1.", ""),
                            new CharacterFeat("Saltador Constante", "Você é extremamente acostumado a saltar, movendo-se mais através de pulos do que correndo. Ao pular, caso você esteja no alcance toque de uma parede ou objeto no fim do seu movimento, você pode utilizar a ação pular mais uma vez como ação livre, cortando seu pulo pela metade, ao terminar o movimento com um alvo dentro do seu alcance corpo a corpo, caso realize um ataque contra ele, você recebe +2 na jogada de ataque e, caso acerte, causa dano adicional igual ao seu modificador de Força.", ""),
                            new CharacterFeat("Técnicas Agressivas de Escudo", "Você aperfeiçoa o uso do seu escudo para colocá-lo no seu ataque. Ao atacar no seu turno, você pode usar sua Ação Bônus para Empurrar com o escudo. Caso o alvo seja empurrado com sucesso, ele recebe Xd6 + seu Modificador de Força de dano de impacto, onde X é igual ao seu Modificador de Força. Além disso, você pode escolher aumentar a distância que a criatura é empurrada em 4,5 metros ou a derrubar.", ""),
                            new CharacterFeat("Técnicas de Arremesso", "Você se aprofunda em técnicas para manusear armas de arremesso no seu potencial máximo e evitar desperdiçar uma delas. Sempre que atacar com uma arma de arremesso, você recebe um bônus de +2 para acertar e +3 no dano.", ""),
                            new CharacterFeat("Técnicas de Reação Rápida", "Preparado para agir sob pressão e urgência, você sabe como reagir o mais rápido possível. Você recebe +5 de Iniciativa. Após a rolagem de iniciativa, caso você não seja o primeiro, você pode rolar novamente, ficando com o melhor resultado.", ""),
                            new CharacterFeat("Técnicas Defensivas de Escudo", "Você aperfeiçoa o uso do seu escudo para colocá-lo por completo na sua defesa. Ao invés de receber penalidade, você adiciona o bônus padrão do escudo em TRs de Reflexos. Além disso, uma quantidade de vezes igual ao seu Bônus de Treinamento, por descanso longo, você pode, antes de saber o resultado de um TR de Reflexos, escolher usar sua Reação para reduzir o valor necessário para um sucesso crítico em 3.", ""),
                            new CharacterFeat("Tempestade de Ideias", "Você decide extrair ao máximo o seu potencial, obtendo melhorias e novas maestrias. Aumenta um atributo a sua escolha em 1. Você se torna treinado em uma perícia e uma ferramenta à sua escolha. Além disso, escolha uma perícia na qual seja treinado: uma quantidade de vezes igual a metade do seu bônus de treinamento, por descanso curto, você pode escolher receber vantagem em um teste com ela.", ""),
                            new CharacterFeat("Adepto de Medicina", "Estudando em seu tempo livre, você aprendeu sobre primeiros socorros em busca de ajudar sua equipe em momentos de desespero. Ao obter este talento, você recebe acesso ao segundo efeito da habilidade Suporte em Combate, de Suporte (p.102), com o valor da cura sendo baseado em seu nível de personagem, mas a quantidade de usos é reduzida pela metade.", "[Pré-Requisito: Mestre em Medicina, não possuir mais que dois talentos com o nome \"Adepto\"]"),
                            new CharacterFeat("Adepto de Briga", "Para sempre ter uma opção, você treinou seus punhos o suficiente para ajudar nas situações mais precárias. Enquanto não estiver com nenhum equipamento do grupo Pugilato, você recebe +3 em jogadas de ataque desarmado e o dano de seus golpes desarmados aumenta em 2 níveis. Além disso, caso acerte um ataque desarmado mas não cause nenhum dano, você pode Agarrar, Derrubar ou Empurrar o alvo como uma Ação Livre, recebendo um bônus igual a metade do seu Bônus de Treinamento no teste.", "[Pré-Requisito: Mestre em Atletismo, não possuir mais que dois talentos com o nome \"Adepto\"]"),
                            new CharacterFeat("Adepto de Combate", "Estudando e refletindo, você consegue adotar um estilo de combate específico, compreendendo e incorporando seus detalhes. Ao obter este talento você aprende um dos estilos de combate da especialização Especialista em Combate, o qual considera seu Nível de Personagem para os efeitos.", "[Pré-Requisito: Mestre em Intuição, não possuir mais que dois talentos com o nome \"Adepto\"]"),
                            new CharacterFeat("Adepto de Feitiçaria", "Com um treinado mais focado em técnica e como a utilizar de maneira melhor, você descobre mais sobre a feitiçaria como um todo. Ao obter este talento, você recebe uma Mudança de Fundamento da habilidade Domínio dos Fundamentos de Especialista em Técnica (p.78), com exceção de Técnica Rápida. Você pode reduzir o custo da Mudança de Fundamento em 1 uma quantidade de vezes igual ao seu bônus de treinamento por cena.", "[Pré-Requisito: Mestre em Feitiçaria, possuir Feitiços, não possuir mais que dois talentos com o nome \"Adepto\"]"),
                            new CharacterFeat("Alma Inquebrável", "Sua alma é mais resistente do que o normal, com sua consciência e perseverança tornando-a difícil de se quebrar. Você se torna treinado em Integridade e recebe Redução de Dano contra Dano na Alma igual a 1/4 do seu Nível de Personagem.", "[Pré-Requisito: Constituição 14]"),
                            new CharacterFeat("Apaziguador de Técnica", "Preparado para impedir seus inimigos de utilizarem técnicas no meio de combate, você sabe o momento perfeito para esgueirar golpes entre conjurações. Ao ver um inimigo usar uma técnica com a conjuração de Ação Comum ou maior em seu alcance corpo-a-corpo, você pode realizar um golpe de oportunidade contra ela, forçando-a a fazer um teste de concentração. Caso a criatura falhe, ela perde 5 em rolagens de acerto/CD caso seja um Feitiço de dano, tem os benefícios do Feitiço cortados pela metade caso seja auxiliar ou tem o Feitiço completamente anulado caso seja especial ou não se encaixe em nenhum dos outros parâmetros. Caso o Feitiço seja anulado, o alvo recupera a ação e não gasta o PE, mas não pode realizar o Feitiço anulado.", "[Pré-Requisito: Treinado em Astúcia, Nível 8]"),
                            new CharacterFeat("Aptidão Desenvolvida", "Você desenvolve uma de suas aptidões e capacidade de uso da energia amaldiçoada. Ao obter este talento, escolha uma aptidão amaldiçoada para ter o seu nível de aptidão aumentado em 1. Você pode pegar esse talento múltiplas vezes, mas apenas uma vez para cada Aptidão.", "[Pré-Requisito: Nível 4]"),
                            new CharacterFeat("Determinado a Viver", "Mesmo de frente a perigos e ameaças sem limites, você mantém sua vontade de viver e seguir em frente. Uma vez por dia, na primeira vez que fosse para os testes de morte, você pode escolher ficar com 1 de vida ao invés disso. Todo teste de morte que você realiza, a partir do segundo, possui vantagem.", "[Pré-Requisito: Treinado em Vontade e Constituição 16]"),
                            new CharacterFeat("Discurso Motivador", "Você pode gastar 10 minutos, fora de combate, ou gastar uma Ação Completa,dentro de combate, para inspirar seus aliados: todas as criaturas amigáveis na cena, que possam te ouvir, recebem HP temporário igual ao dobro do seu nível + seu modificador de carisma multiplicado pela metade do seu bônus de treinamento, arredondado para cima. Uma criatura só pode receber esse bônus uma vez por descanso curto ou longo.", "[Pré-Requisito: Treinado em alguma perícia de Carisma]")
                    )
            );

            featRepository.saveAll(feats);
        }


    }
}
