package com.fmrpg.fmbackend.seeders;

import com.fmrpg.fmbackend.entities.SpecialItems;
import com.fmrpg.fmbackend.enums.SpecialItemCategory;
import com.fmrpg.fmbackend.repositories.SpecialItemRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class SpecialItemsSeeder implements CommandLineRunner {

    private final SpecialItemRepository specialItemRepository;
    @Override
    public void run(String... args) throws Exception {

        if(specialItemRepository.count() > 0) return;

        specialItemRepository.saveAll(
                List.of(
                        new SpecialItems("Antídoto Simples", "Um simples antídoto, capaz de neutralizar venenos mais leves. Como uma ação bônus, um personagem pode consumir um antídoto simples, sendo curado da condição envenenado e/ou qualquer veneno que proveha de uma maldição de terceiro grau ou inferior.", 1, 1, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Brinco de Comunicação", "Um par de brincos imbuídos com uma técnica de comunicação. Usar um desses brincos permite que o usuário sintonize com até 10 outras pessoas que também estejam usando um. Todos sintonizados na mesma conexão conseguem se comunicar mentalmente desde que estejam dentro de 45 metros.", 1, 1, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Chaveiro Canalizador", "Um chaveiro que canaliza energia amaldiçoada, refinando-a e dificultando resistir. Um personagem com o chaveiro canalizador tem a CD dos seus testes de resistência aumentado em 1.", 1, 1, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Injeção Estimulante", "Uma injeção criada a partir de uma mescla de medicina e controle de energia amaldiçoada. Ela tem uma única carga e a injetar faz com que você receba vantagem em toda rolagem usando um atributo a sua escolha, exceto Luta e Pontaria, durante 10 minutos. Dentro de combate, injetar é uma ação bônus.", 1, 1, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Mix Energético Pequeno", "Um conjunto de suplementos e substâncias que conseguem recuperar a energia e vigor físico, concentrados em uma cápsula. Como uma ação bônus, é possível consumir o mix, recuperando 3 pontos de vigor.", 1, 1, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Óleo Amolador", "Um pequeno recipiente cheio de um óleo que aumenta o potencial de uma arma, amolando-a. Pode ser aplicado em duas armas antes de acabar; uma arma coberta com óleo amolador causa 2 de dano adicional do seu tipo. O óleo dura um dia.", 1, 1, SpecialItemCategory.MISTURA),
                        new SpecialItems("Pérola Carregada", "Uma pequena pérola carregada com energia amaldiçoada, usada para recuperar do próprio estoque. Como uma ação bônus, é possível consumir a pérola, recuperando 3 pontos de energia amaldiçoada.", 1, 1, SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Pote de Espírito Curandeiro", "Um pote especial, preenchido com um pequeno espírito amaldiçoado com capacidades curativas, o qual foi domado para uso: como uma ação bônus, você pode liberar o espírito e o comandar a curar uma pessoa dentro de 9 metros de você. A cura é igual a 3d8+6 pontos de vida, e o espírito se esvai após curar uma criatura.", 1, 1 ,SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Remédio Simples", "Um simples remédio, capaz de forçar uma reação regenerativa do corpo. Como uma ação comum, é possível consumir o remédio e gastar seus dados de vida para se curar, com um limite igual a quatro dados de vida.", 1, 1, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Símbolo de Vida", "Uma espécie de pequena ficha ou amuleto, encravado em madeira e imbuído com energia reversa. Como uma ação bônus, é possível o destruir para liberar energia em si mesmo, curando-se em 4d6+4 pontos de vida.", 1, 1, SpecialItemCategory.TALISMÃ),
                        new SpecialItems("Veneno Comum", "Um pote de veneno comum e simples, mas efetivo, o qual pode ser usado para cobrir armas. Um pote pode cobrir até duas armas; uma arma coberta com veneno comum causa 2 de dano venenoso adicional.", 1, 1, SpecialItemCategory.MISTURA),
                        new SpecialItems("Veneno Debilitante", "Um pote de veneno cujo foco é atingir o corpo, debilitando-o. Um pote pode cobrir até duas armas; quando um ataque com uma arma coberta com veneno debilitante acertar, o alvo do ataque deve realizar um teste de resistência de Fortitude com CD12 mais bônus de maestria de quem o criou mais bônus do atributo usado pelo portador da arma; caso falhe, a criatura tem o seu movimento reduzido pela metade. O veneno dura até que esse efeito seja aplicado uma quantidade de vezes igual ao bônus de maestria de quem o criou.", 1, 1, SpecialItemCategory.MISTURA),
                        new SpecialItems("Veneno Intenso", "Um pote de veneno intenso e concentrado, com o propósito de invadir o corpo do alvo. Um pote pode cobrir até duas armas; quando um ataque com uma arma coberta com veneno intenso acertar, o alvo deve realizar um teste de resistência de Fortitude com CD12 mais bônus de maestria de quem o criou mais bônus do atributo usado pelo portador da arma; caso falhe, a criatura recebe a condição Envenenado, a qual dura uma rodada. O veneno dura até que esse efeito seja aplicado uma quantidade de vezes igual ao bônus de maestria de quem o criou.", 1, 1, SpecialItemCategory.MISTURA),
                        new SpecialItems("Amuleto do Vislumbre", "Um amuleto amaldiçoado, que fornece ao portador capacidade de vislumbrar tudo ao seu redor com perfeição, superando dificuldades. O usuário desse item recebe visão no escuro com alcance de 9 metros, além de um bônus de +3 em rolagens de Percepção. Além disso, uma vez ao dia, você pode, como uma ação bônus, se tornar capaz de enxergar com os olhos fechados por 1 minuto.", 1, 2, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Antídoto Intermediário", "Um antídoto de complexidade mediana, que consegue neutralizar toxinas de maior nível. Como uma ação bônus, um personagem pode consumir um antídoto intermediário, sendo curado da condição envenenado e/ou qualquer veneno que provenha de uma maldição de primeiro grau ou inferior.", 1, 2, SpecialItemCategory.MISTURA),
                        new SpecialItems("Apanhador de Saúde", "Um pequeno amuleto com formato semelhante ao de um apanhador de sonhos, o qual atraí boas energias. Sempre que um portador do acessório for curado, recebe +1 de cura por dado, com um limite de cura adicional igual ao seu bônus de maestria.", 1, 2, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Bracelete do Vigor", "Um bracelete que entra em sintonia com o corpo e acentua o físico, concedendo um maior vigor para o seu portador. Enquanto estiver utilizando o bracelete do vigor, os seus pontos de vida máximos aumentam em 10.", 1, 2, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Conjunto de Pérolas Carregadas", "Um conjunto de pérolas carregadas com energia amaldiçoada. Como uma ação bônus, é possível consumir o conjunto de pérolas, recuperando 6 pontos de energia amaldiçoada.", 1, 2, SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Faixa de Foco", "Uma faixa que quando presa ao seu portador o permite focar e manter a concentração. Você recebe um bônus de +3 em testes para manter a concentração e, duas vezes por dia, você pode escolher não perder a concentração ao invés de realizar um teste.", 1, 2, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Mix Energético Médio", "Um conjunto reforçado de suplementos e substâncias que aumentam a recuperação do vigor físico. Como uma ação bônus, é possível consumir o mix, recuperando 6 pontos de vigor.", 1, 2, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Pote de Espírito Curandeiro Elevado", "Um pote com um espírito curandeiro de nível elevado, com capacidades amplificadas: como uma ação bônus, você pode liberar o espírito e o comandar a curar uma pessoa dentro de 12 metros de você. A cura é igual a 4d12+12, e o espírito se esvai após curar uma criatura.", 1, 2, SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Pulseira Magistal", "Uma pulseira cujas propriedades conseguem extrair mais as capacidades de quem a usar, melhorando uma perícia. Enquanto estiver usando a pulseira magistral, o usuário recebe Maestria em uma perícia a sua escolha.", 1, 2, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Remédio Intermediário", "Um remédio mais complexo, capaz de forçar uma reação regenerativa avançada no corpo. Como uma ação comum, é possível consumir o remédio e gastar seus dados de vida para se curar, com um limite igual a oito dados de vida.", 1, 2, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Revigorante", "Um remédio que é capaz de retirar o cansaço excessivo do corpo daquele que o consome. Como uma ação bônus, pode tomar um revigorante, removendo um nível de exaustão e fazendo com que o remédio se desmanche.", 1, 2, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Símbolo de Vida Florescente", "Uma ficha ou amuleto encravado em madeira e com quantidades modestas de energia reversa, o que dá um sutil brilho e calor. Como uma ação bônus, é possível o destruir para liberar energia em si mesmo, curando-se em 6d8+12 de vida.", 1, 2, SpecialItemCategory.TALISMÃ),
                        new SpecialItems("Talismã de Barreira Superior", "Melhorando no talismã de barreira, ela é tecida com mais cuidado e foco em uma maior agilidade. Pode usá-lo como uma ação bônus ou como uma reação, invocando quatro paredes, cada uma possuindo 25 pontos de vida e ocupando 1,5 metros cada. Após usado, o talismã se esvai.", 1, 2, SpecialItemCategory.TALISMÃ),
                        new SpecialItems("Talismã Protetivo", "Um talismã confeccionado com foco na proteção contra uma fonte específica. Enquanto estiver usando o talismã protetivo, o usuário recebe resistência a um tipo de dano elemental a sua escolha. Só se pode utilizar um talismã por vez.", 1, 2, SpecialItemCategory.TALISMÃ),
                        new SpecialItems("Veneno Desnorteante", "Um pote de veneno cuja composição foca em atingir o sistema nervoso de uma criatura. Um pote pode cobrir até duas armas; quando uma arma coberta com o veneno desnorteante acertar, o alvo deve realizar um teste de resistência de Fortitude com CD12 mais bônus de maestria de quem o criou mais bônus do atributo usado pelo portador da arma; caso falhe, a criatura recebe a condição Desprevenido, a qual dura uma rodada. O veneno dura até que esse efeito seja aplicado uma quantidade de vezes igual ao bônus de maestria de quem o criou.", 1, 2, SpecialItemCategory.MISTURA),
                        new SpecialItems("Anéis do Conhecimento", "Um conjunto de peculiares anéis, forjados e imbuídos com energia amaldiçoada e conhecimentos, prendendo-se na pele e se conectando ao usuário. Os anéis aumentam o valor de Sabedoria do usuário em 2, podendo superar o seu limite de atributo, até o máximo de 30.",1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Antídoto Absoluto", "Um antídoto absoluto, confeccionado com a mais refinada medicina, capaz de neutralizar qualquer veneno ou toxina. Como uma ação bônus, um personagem pode consumir um antídoto absoluto, sendo curado da condição envenenado e/ou qualquer veneno que provenha de uma maldição de qualquer grau, inclusive especial.",1,2,SpecialItemCategory.MEDICINA),
                        new SpecialItems("Bracelete de Força", "Firme e forjado a partir do mais forte aço, esse bracelete aumenta o valor de Força do usuário em 2, podendo superar o seu limite de atributo, até o máximo de 30.", 1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Bracele do Vigor Superior", "Uma versão superior do bracelete do vigor, concedendo ainda mais vitalidade e vigor ao portador. Enquanto estiver utilizando o bracelete do vigor superior, os seus pontos de vida máximos aumentam em 15.",1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Chaveiro Absorsor", "Um pequeno adereço espiritual, semelhante a um chaveiro, o qual é capaz de absorver energia amaldiçoada a partir de vestígios. Sempre que eliminar um inimigo que possua energia amaldiçoada ou seja formado por energia, você recupera 2 pontos de energia amaldiçoada.",1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Cinturão do Inabalável", "Um robusto cinturão metálico, com uma correnteza de energia amaldiçoada que é transmitida e reforça o físico do usuário. O cinturão aumenta o valor de Constituição do usuário em 2, podendo superar o seu limite de atributo, até o máximo de 30.",1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Domínio Simples Contido", "Um pequeno tubo com um domínio simples armazenado. Pode ser usado como uma ação comum, erguendo um domínio simples sem custo de energia, o qual se mantém por até 2 rodadas, protegendo apenas o portador do item. Após ser usado, o tubo se torna inútil, com a técnica armazenada se esvaindo",1,3,SpecialItemCategory.TALISMÃ),
                        new SpecialItems("Faixas Céleres", "Várias faixas leves e quase transparentes, as quais quando amarradas em uma pessoa, usam da energia imbuída para estimular os reflexos e agilidade. As faixas aumentam o valor de Destreza do usuário em 2, podendo superar o seu limite de atributo, até o máximo de 30.",1,3, SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Laço de Vida", "Um pequeno laço vermelho, imbuído com quantidades excessivas de energia reversa. Um feiticeiro que tenha o laço preso a si é capaz de se prender a vida: caso um personagem com um laço da vida vá morrer, tal morte é ignorada e o laço se desgasta, sumindo.", 1,3,SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Mistura Profana", "Uma mistura profana, composta a partir de energia amaldiçoada concentrada e em estado ativo, capaz de estimular o fluxo interno de energia de um feiticeiro, mas possuindo um preço. Como uma ação comum, pode-se consumir a mistura profana, reduzindo o custo de todas as habilidades que utilizem energia amaldiçoada em 1 ponto, durante uma cena. Após o fim da cena, você também recebe um nível de exaustão",1,3,SpecialItemCategory.MISTURA),
                        new SpecialItems("Mix Energético Grande", "Uma pílula robusta e com concentrações extremas de substâncias que recuperam o físico e vigor. Como uma ação bônus, é possível consumir o mix, recuperando 10 pontos de vigor.", 1,3, SpecialItemCategory.MEDICINA),
                        new SpecialItems("Ornamento Fascinante", "Um ornamento com joias e uma beleza notável, além de um toque do jujutsu para o conceder um aspecto agradável que um acessório não poderia alcançar normalmente. O ornamento aumenta o valor de Carisma do usuário em 2, podendo superar o seu limite de atributo, até o máximo de 30.", 1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Pingente do Intelecto", "Leve, sutil e coberto de inscrições anciãs, esse pingente aumenta o valor de Inteligência do usuário em 2, podendo superar o seu limite de atributo, até o máximo de 30.",1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Pomada Reforçadora", "Uma pomada especial capaz de reforçar o corpo contra danos específicos. Um recipiente de pomada pode ser aplicado em até três pessoas. Uma pessoa que tenha a pomada aplicada recebe resistência a um tipo de dano a sua escolha até o próximo descanso. Caso a pessoa já seja resistente, a pomada forma uma camada protetiva: o dano de uma quantidade de ataques cujo dano seja do tipo escolhido, igual ao bônus de maestria do criador do item, é reduzido a zero; após isso, recebe-se 15 de redução de dano contra o tipo escolhido até o próximo descanso, com a pomada se desgastando após isso. Dentro de combate, aplicar a pomada é uma ação comum.", 1,3,SpecialItemCategory.MEDICINA),
                        new SpecialItems("Pote de Espírito Curandeiro Transcendido", "Um pote com um espírito curandeiro que transcende os limites, com capacidades quase máximas: como uma ação bônus, você pode liberar o espírito e o comandar a curar uma pessoa dentro de 18 metros de você. A cura é igual a 8d12+24 e pode se remover uma condição da criatura curada, e o espírito se esvai após curar uma criatura.", 1,3, SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Pulseira Primacial", "Uma pulseira especial, a qual consegue levar além uma perícia do usuário. Enquanto estiver usando a pulseira primacial, o usuário se torna especialista em uma perícia a sua escolha, exceto Luta e Pontaria, desde que já possua maestria nela.", 1,3,SpecialItemCategory.ACESSORIO),
                        new SpecialItems("Remédio Complexo", "Um remédio de criação complexa. Como uma ação comum, é possível consumir o remédio e gastar seus dados de vida para se curar, com um limite igual a doze dados de vida.", 1,3,SpecialItemCategory.MEDICINA),
                        new SpecialItems("Terço de Pérolas Carregadas", "Um terço criado a partir de pérolas carregadas com energia amaldiçoada. Como uma ação bônus, é possível consumir o terço, recuperando 10 pontos de energia amaldiçoada.",1,3,SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Veneno Maldito","Um veneno feito a partir de uma substância semelhante ao sangue de maldições, com propriedades extremamente nocivas. Um pote pode cobrir até duas armas; quando uma arma coberta com o veneno maldito acertar, o alvo deve realizar um teste de resistência de Fortitude com CD14 + bônus de maestria de quem o criou + bônus do atributo usado pelo portador da arma; caso falhe, a criatura recebe a condição Exposto, a qual dura duas rodadas, e fica condenado até o final da cena. O veneno dura até que esse efeito seja aplicado uma quantidade de vezes igual ao bônus de maestria de quem o criou", 1,3,SpecialItemCategory.MISTURA),
                        new SpecialItems("Elixir de Vida", "Sendo o suprassumo da medicina, o elixir da vida incita uma vitalidade sem precedentes naquele que o consumir. Como uma ação bônus, é possível consumir o elixir da vida, podendo usar todos os seus dados de vida para se curar, somando o dobro do seu modificador de constituição em cada um; você recebe vantagem e +10 em rolagens de Fortitude pelo resto da cena, assim como em Integridade.", 1,4,SpecialItemCategory.MEDICINA),
                        new SpecialItems("Lágrima de Shinigami", "O mais letal veneno já conhecido, capaz de imbuir uma arma com tamanha letalidade que passou a ser conhecido como a lágrima de um shinigami. Devido a sua escassez, um pote de lágrima de shinigami pode cobrir apenas uma arma; quando uma arma coberta com a lágrima de shinigami acertar, o alvo deve realizar um teste de resistência de Fortitude com CD20 + bônus de maestria de quem o criou + o bônus do atributo usado pelo portador da arma; caso falhe, a criatura recebe a condição Amaldiçoado até o final da cena, se suceder, recebe apenas as condições Amedrontado e Exposto, as quais duram duas rodadas. Uma criatura amaldiçoada gasta 2 pontos de energia a mais sempre que usar energia amaldiçoada e tem a sua CA diminuída em 4. Enquanto o veneno durar, a arma também causa 3d10 de dano adicional Ácido ou Necrótico, a escolha do portador. O veneno dura até que esse efeito seja aplicado uma quantidade de vezes igual a metade do bônus de maestria de quem o criou.", 1,4,SpecialItemCategory.MISTURA),
                        new SpecialItems("Pote de Espírito de Vida", "Um pote com um misterioso espírito que é constituído de pura energia reversa, ao invés de energia amaldiçoada, servindo como uma fonte de vida: como uma ação bônus, você pode liberar o espírito e o comandar a curar uma pessoa dentro de 36 metros de você. A cura restaura completamente os pontos de vida da criatura e remove qualquer condição e veneno que ele possua.", 1,4,SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Símbolo de Vida Absoluta", "Encravado e entalhado com os símbolos de absoluta saúde e vida, esse símbolo consegue canalizar em sua máxima a vida. Como uma ação livre, é possível o destruir para liberar energia em si mesmo, recuperando todos os seus pontos de vida, até o máximo, além de receber pontos de vida temporários igual ao triplo do seu nível de personagem.",1,4,SpecialItemCategory.ESPIRITUAL),
                        new SpecialItems("Talismã do Ápice", "Um talismã que quando destruído liberta uma quantidade excessiva de energia, a qual é direcionada a um atributo específico do usuário. Ao usar o talismã, o valor de um atributo a sua escolha se torna 30 durante uma hora e ele se quebra", 1,4,SpecialItemCategory.TALISMÃ),
                        new SpecialItems("Ferramentas de Alfaiate", "O kit de ferramentas de alfaiate é focado na criação de acessórios especiais, feitos sob medida com o uso da habilidade manual e do jujutsu. Entretanto, criar acessórios amaldiçoados é complexo e custoso: do nível 1 ao 9, você só pode criar 1 acessório por interlúdio; a partir do nível 10 você pode criar 2 acessórios por interlúdio.", 1,5, SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Alquimia", "O kit de ferramentas de alquimia possibilita misturar elementos e substâncias para criar algo novo, podendo ser tanto venenos quanto misturas com efeitos diferenciados. Possuir maestria em ferramentas de alquimia permite criar itens especiais do tipo Mistura; não há um limite de quantas misturas podem ser criadas.", 1,5,SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Armeiro", "O kit de ferramentas de armeiro é o principal para se manter os equipamentos em um bom estado, realizando a sua manutenção e otimização, permitindo assim que o máximo do seu potencial seja extraído. Durante um descanso curto, um personagem com maestria em ferramentas de armeiro pode melhorar temporariamente uma quantidade de equipamentos igual ao seu bônus de maestria; em um descanso longo, essa quantidade é igual ao dobro. Uma arma melhorada adiciona o bônus de maestria do armeiro em rolagens de dano; um escudo melhorado adiciona o bônus de maestria do armeiro no seu bônus na Classe de Armadura. As melhorias duram até o próximo descanso ou com algum desgaste extremo, definido pelo Narrador.",1,5,SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Canalizador", "O kit de ferramentas de canalizador é um conjunto de peculiares amuletos, pérolas e outros itens espirituais, que permitem canalizar energia amaldiçoada e alguns espíritos amaldiçoados menores em itens. Possuir maestria em ferramentas de canalizador permite criar itens especiais do tipo Espiritual; não há um limite de quantos itens espirituais podem ser criados.", 1,5,SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Cozinheiro", "O kit de ferramentas de cozinheiro dá a capacidade de extrair ao máximo habilidades culinárias, criando refeições da maior qualidade, as quais passam a até mesmo conferir benefícios para aqueles que as consumirem. Ter maestria em ferramentas de cozinheiro permite produzir refeições com propriedades especiais. Durante um descanso curto, um personagem com maestria nas ferramentas de cozinheiro pode criar uma refeição com uma quantidade de propriedades igual a metade do seu bônus de maestria; em um descanso longo, o valor é igual ao bônus de maestria. As propriedades são as seguintes: • Cativante. Consumir uma refeição cativante concede pontos de alma temporários igual a 5 multiplicado pelo bônus de maestria do cozinheiro. • Energética. Consumir uma refeição energética concede energia amaldiçoada temporária igual ao dobro do bônus de maestria do cozinheiro. • Leve. Consumir uma refeição leve concede um aumento na quantidade de movimento igual a 1,5 metros multiplicado pela metade bônus de maestria do cozinheiro. Esse efeito dura até o próximo descanso. • Nutritiva. Consumir uma refeição nutritiva concede um bônus de 2d3 em uma quantidade de testes de resistência igual ao dobro do bônus de maestria do cozinheiro. • Picante. Consumir uma refeição picante concede um bônus em rolagens de acerto igual a metade do bônus de maestria do cozinheiro. Esse bônus dura até o próximo descanso. • Reforçada. Consumir uma refeição reforçada concede um bônus na Classe de Armadura igual ao bônus de maestria do cozinheiro. Esse bônus dura até o próximo descanso. • Refrescante. Consumir uma refeição refrescante permite que quem a comeu faça as próximas rolagens de perícia com vantagem, uma quantidade de vezes igual ao bônus de maestria do cozinheiro. • Revigorante. Consumir uma refeição revigorante concede pontos de vida temporários igual a 5 multiplicado pelo bônus de maestria do cozinheiro.", 1,5,SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Entalhador", "O kit de ferramentas de entalhador junta instrumentos e utensílios utilizados na arte de se entalhar e encravar, a qual quando unida a energia amaldiçoada permite criar amuletos e talismãs. Possuir maestria em ferramentas de entalhador permite criar itens especiais do tipo Talismã; não há um limite de quantos talismãs podem ser criados.", 1,5,SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Ferreiro", "O kit de ferramentas de ferreiro é utilizado na criação e melhoria de armas e escudos, eventualmente utilizando do jujutsu para as transformar em ferramentas amaldiçoadas. Possuir maestria nas ferramentas de ferreiro permite criar tanto equipamentos comuns quanto ferramentas amaldiçoadas.", 1,5,SpecialItemCategory.FERRAMENTAS),
                        new SpecialItems("Ferramentas de Médico", "O kit de ferramentas de médico permite cuidar efetivamente da saúde, além de sintetizar substâncias medicinais refinadas, criando antídotos ou remédios. Possuir maestria nas ferramentas de médico permite criar itens especiais do tipo Medicina; não há um limite de quantas medicinas podem ser criadas.", 1,5,SpecialItemCategory.FERRAMENTAS)
                )
        );
    }
}
