package com.fmrpg.fmbackend.dtos;

public record CharacterSKillDto(
        Integer acrobatics,
         Integer cunning,
         Integer athletics,
         Integer driving,
         Integer deception,
         Integer spellcasting,
         Integer fortitude,
         Integer stealth,
         Integer history,
         Integer integrity,
         Integer intimidation,
         Integer insight,
         Integer investigation,
         Integer fighting,
         Integer medicine,
         Integer occultism,
         Integer crafting,
         Integer perception,
         Integer persuasion,
         Integer performance,
         Integer marksmanship,
         Integer sleightOfHand,
         Integer reflexes,
         Integer religion,
         Integer survival,
         Integer technology,
         Integer willPower
) { }
